---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Apply deployment
      kubernetes.core.k8s:
        state: present
        src: manifests/nginx-deployment.yaml

    - name: Apply service
      kubernetes.core.k8s:
        state: present
        src: manifests/nginx-service.yaml